name: ci

on:
  push:
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "Makefile"
      - ".github/workflows/ci.yml"
  schedule:
    # JST 11:00 (UTC 02:00), 月-金
    - cron: "0 2 * * 1-5"

jobs:
  ci:
    name: CI (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          # - ubuntu-24.04-arm
          # - macos-26
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
      - run: rustup update stable
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libpulse-dev libx11-dev
      - run: cargo fmt --all --check
      - name: Clippy
        run: cargo clippy --workspace -- -D warnings
      - name: Test
        run: cargo test --workspace

  slack_notify:
    needs: [ci]
    timeout-minutes: 5
    runs-on: ubuntu-slim
    if: ${{ always() }}
    permissions:
      actions: read
    steps:
      - name: Slack Notification
        uses: shiguredo/github-actions/.github/actions/slack-notify@main
        with:
          status: ${{ job.status }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack_channel: zakuro
          notify_mode: failure_and_fixed
